<a href="https://colab.research.google.com/github/kaarimaa/on29-python-s09-pandas-numpy-I/blob/main/exercicios/para-casa/exercicio_de_casa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('data_sample_SP.csv' , sep=';' , encoding='latin-1', on_bad_lines='skip')
#Importando os dados necessários com a separação no formato ideal

In [44]:
df

,Data,Hora UTC,PRECIPITAO TOTAL. HORARIO (mm),PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO. HORARIA (mB),PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m2),TEMPERATURA DO AR - BULBO SECO. HORARIA (C),TEMPERATURA DO PONTO DE ORVALHO (C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C),...,VENTO. RAJADA MAXIMA (m/s),VENTO. VELOCIDADE HORARIA (m/s),REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,DATA DE FUNDACAO
0,2021/07/31,1100 UTC,0.0,925.4,925.6,925.0,312.6,8.0,3.8,8.0,...,8.3,2.8,SE,SP,BRAGANCA PAULISTA,A744,-22.951944,-46.530556,891.00,20/12/17
1,2020/01/16,0800 UTC,0.0,944.1,944.1,943.3,NaN,20.4,19.3,20.6,...,1.9,1.3,SE,SP,ITUVERAVA,A753,-20.359722,-47.775278,610.58,17/07/08
2,2021/08/25,1900 UTC,0.0,899.4,899.7,899.3,1649.2,30.9,1.3,31.6,...,4.3,0.7,SE,SP,FRANCA,A708,-20.584444,-47.382500,1002.74,12/12/02
3,2021/08/02,1600 UTC,0.0,978.6,979.5,978.6,2545.3,27.1,7.5,27.5,...,5.8,2.2,SE,SP,VALPARAISO,A734,-21.319167,-50.930278,381.90,30/08/07
4,2020/07/25,1400 UTC,NaN,932.8,932.9,932.8,NaN,25.6,9.2,25.8,...,8.3,3.6,SE,SP,AVARE,A725,-23.101667,-48.941111,776.36,22/09/06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2020/08/22,0300 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,SE,SP,SAO SEBASTIAO,A767,-23.810833,-45.402500,24.00,25/10/17
99996,2020/08/03,1900 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,SE,SP,BEBDOURO,A764,-20.949167,-48.490000,790.00,27/10/16
99997,2021/08/13,2200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,SE,SP,SAO SEBASTIAO,A767,-23.810833,-45.402500,24.00,25/10/17
99998,2022/10/28,2100 UTC,6.4,957.2,958.0,957.1,256.3,27.3,18.0,28.5,...,10.6,0.1,SE,SP,LINS,A727,-21.666111,-49.734722,460.65,20/09/06
99999,2022/07/13,0700 UTC,0.0,959.7,959.7,959.5,NaN,18.0,13.6,18.9,...,3.5,0.3,SE,SP,IBITINGA,A737,-21.855556,-48.799722,496.75,09/11/07

In [45]:
df['TEMPERATURA DO AR - BULBO SECO. HORARIA (C)'].describe()
#descrição dos dados a serem utilizados do daframe

count    71889.000000
mean        21.178566
std          7.655026
min        -50.900000
25%         17.800000
50%         21.400000
75%         25.400000
max         42.900000
Name: TEMPERATURA DO AR - BULBO SECO. HORARIA (C), dtype: float64

In [46]:
df['TEMPERATURA DO AR - BULBO SECO. HORARIA (C)'].mean()
#media da temperatura do ar

21.178565566359246

In [50]:
df = df.dropna(subset=['RADIACAO GLOBAL (Kj/m2)'])
df.shape
#retirar nulos da coluna Radiação Global

(41556, 27)

In [55]:
df[3:3]
df.columns
df[['ALTITUDE', 'ESTACAO' , 'VENTO. VELOCIDADE HORARIA (m/s)']]
#reduzindo para 3 colunas

       ALTITUDE                 ESTACAO  VENTO. VELOCIDADE HORARIA (m/s)
0        891.00       BRAGANCA PAULISTA                              2.8
2       1002.74                  FRANCA                              0.7
3        381.90              VALPARAISO                              2.2
7         24.00           SAO SEBASTIAO                              4.8
8        771.00  SAO PAULO - INTERLAGOS                              1.4
...         ...                     ...                              ...
99988    660.00                 MARILIA                              NaN
99990   1285.00               CRIOSFERA                             10.0
99991    540.41              PRADOPOLIS                              1.3
99992    498.00                    TUPA                              NaN
99998    460.65                    LINS                              0.1

[41556 rows x 3 columns]

In [59]:
df_normalizado = df.copy()
coluna = "TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C)"
df_normalizado [coluna]
#normalizando coluna

0         8.0
2        31.6
3        27.5
7        21.1
8        22.6
         ...
99988    25.4
99990   -46.5
99991    29.2
99992    33.0
99998    28.5
Name: TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C), Length: 41556, dtype: float64